name: Android Build

on:
  push:
    branches: [main, master, fdroid-publish, feat/react-native-camera-foss]
    tags: ["v*"]
  pull_request:
    branches: [main, master, fdroid-publish, feat/react-native-camera-foss]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Prebuild Android
        run: npx expo prebuild --platform android --clean

      - name: Make Gradlew executable
        run: chmod +x android/gradlew

      - name: Create keystore for release build
        run: |
          mkdir -p android/app
          keytool -genkey -v -keystore android/app/release.keystore -alias albumcam -keyalg RSA -keysize 2048 -validity 10000 -storepass password -keypass password -dname "CN=AlbumCam, OU=AlbumCam, O=AlbumCam, L=City, ST=State, C=US"

      - name: Build Android Release APK
        run: |
          cd android
          echo "MYAPP_RELEASE_STORE_FILE=release.keystore" >> gradle.properties
          echo "MYAPP_RELEASE_KEY_ALIAS=albumcam" >> gradle.properties
          echo "MYAPP_RELEASE_STORE_PASSWORD=password" >> gradle.properties
          echo "MYAPP_RELEASE_KEY_PASSWORD=password" >> gradle.properties
          ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Get APK info
        id: apk_info
        run: |
          APK_PATH="android/app/build/outputs/apk/release/app-release.apk"
          APK_SIZE=$(du -h "$APK_PATH" | cut -f1)
          APK_SHA256=$(sha256sum "$APK_PATH" | cut -d' ' -f1)
          echo "size=$APK_SIZE" >> $GITHUB_OUTPUT
          echo "sha256=$APK_SHA256" >> $GITHUB_OUTPUT
          echo "path=$APK_PATH" >> $GITHUB_OUTPUT

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            android/app/build/outputs/apk/release/app-release.apk
          name: "AlbumCam ${{ github.ref_name }}"
          body: |
            ## AlbumCam ${{ github.ref_name }}

            ### 📱 Download
            - **APK Size:** ${{ steps.apk_info.outputs.size }}
            - **SHA256:** `${{ steps.apk_info.outputs.sha256 }}`

            ### 📋 Installation
            1. Download the APK file below
            2. Enable "Install from unknown sources" in Android settings
            3. Install the APK
            4. Grant camera and storage permissions when prompted

            ### ✨ What's New
            See the [changelog](https://github.com/sigmaSd/AlbumCam/blob/master/CHANGELOG.md) for detailed changes.

            ### 🔒 Security
            This APK is automatically built from source code using GitHub Actions. You can verify the build process in the [Actions tab](https://github.com/sigmaSd/AlbumCam/actions).

            ### 🛡️ F-Droid
            This app is now F-Droid compatible using react-native-camera instead of expo-camera.
          draft: false
          prerelease: false
          generate_release_notes: true
